# Generated by Django 4.1.7 on 2023-04-20 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_bee', '0003_studyplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionRecord',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='title',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='type',
            field=models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
