# Generated by Django 4.1.7 on 2023-04-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_answer',
        ),
    ]
