# Generated by Django 4.1.7 on 2023-04-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_post_is_answered_remove_post_total_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
